# Generated by Django 2.1.5 on 2020-05-31 20:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Start Date & Time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End Date & Time')),
                ('total_budget', models.DecimalField(decimal_places=2, help_text='Minimum $25', max_digits=11, validators=[django.core.validators.MinValueValidator(25)])),
                ('daily_budget', models.DecimalField(decimal_places=2, help_text='Minimum $25', max_digits=11, validators=[django.core.validators.MinValueValidator(25)])),
                ('status', models.CharField(choices=[('AC', 'Active'), ('PA', 'Paused'), ('DE', 'Deleted')], default='PA', max_length=2)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['update_date'],
            },
        ),
        migrations.CreateModel(
            name='Creative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('target_url', models.URLField(verbose_name='Target URL')),
                ('inventory_type', models.CharField(blank=True, choices=[('RE', 'Rewarded video'), ('IN', 'Interstitial video')], max_length=2, null=True)),
                ('skip_sec', models.PositiveSmallIntegerField(blank=True, default=5, null=True)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('PA', 'Paused'), ('DE', 'Deleted')], default='PA', max_length=2)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsp.Campaign')),
            ],
            options={
                'ordering': ['update_date'],
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Start Date & Time')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='End Date & Time')),
                ('total_budget', models.DecimalField(decimal_places=2, help_text='Minimum $25', max_digits=11, validators=[django.core.validators.MinValueValidator(25)])),
                ('daily_budget', models.DecimalField(decimal_places=2, help_text='Minimum $25', max_digits=11, validators=[django.core.validators.MinValueValidator(25)])),
                ('bid', models.DecimalField(decimal_places=2, help_text='Minimum $0.01', max_digits=11, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('geo_position', models.TextField(blank=True, max_length=200, null=True, verbose_name='GEO-position')),
                ('categories', models.TextField(blank=True, max_length=200, null=True)),
                ('device_types', models.TextField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('AC', 'Active'), ('PA', 'Paused'), ('DE', 'Deleted')], default='PA', max_length=2)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dsp.Campaign')),
            ],
            options={
                'ordering': ['update_date'],
            },
        ),
        migrations.AddField(
            model_name='creative',
            name='strategies',
            field=models.ManyToManyField(to='dsp.Strategy'),
        ),
    ]
