# Generated by Django 2.1.5 on 2020-06-09 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Start Date & Time'),
        ),
    ]
