# Generated by Django 2.1.5 on 2020-06-09 18:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsp', '0002_auto_20200609_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='start_datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Start Date & Time'),
        ),
    ]
