# Generated by Django 2.1.5 on 2020-06-15 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsp', '0003_auto_20200609_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(200)]),
        ),
    ]
